# Generated by Django 3.1 on 2021-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthproblem',
            name='image',
            field=models.ImageField(blank=True, upload_to='healthproblems'),
        ),
    ]
